apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phoenix-app.fullname" . }}
  labels:
    {{- include "phoenix-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "phoenix-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "phoenix-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: phoenix-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
